### ISSUE TITLE
dependency and license?

### ISSUE THREAD

**Issue by Cravix** [zhanlangsir/Qtqq#10]
I wrote a PKGBUILD for qtqq here: http://pastebin.com/uW4rdGRK
but i still need to know about qtqq's dependency and license.
so, qtqq requires what package? please specify it, and thanks in advance:-)
(also, qtqq doesn't show images here, should i install other packages?)

**Comment by zhanlangsir** [comment]
Except the qt library, Just mpg123. Others library i had add there source
to qtqq project.

2012/6/21 Cravix <
reply@reply.github.com

**Comment by Cravix** [comment]
sorry i forget this issue= =
ok, i've packaged it just now, and pkgbuild is at https://aur.archlinux.org/packages.php?ID=61677
and can you tell me the license you use for qtqq? i'm not sure about that, so i write "custom license" in pkgbuild.
(also, if you have advice for package description, just tell me and i'll change it :-)

**Comment by zhanlangsir** [comment]
Thank you for work! The license of qtqq is GPL.

2012/8/9 Cravix notifications@github.com

**Comment by Cravix** [comment]
ok, thank you for your work;-)
