### ISSUE TITLE
关闭以后进程还未结束

### ISSUE THREAD

**Issue by coconut-star** [zhanlangsir/Qtqq#12]
是6月22日更新以后出现的小BUG

**Comment by zhanlangsir** [comment]
现在关闭方式不是点关闭按钮了，那只是缩小，指示器上qtqq的图标还是在的。要在qtqq指示器图标上右键，选择退出才会真正退出~就是win下的缩小到托盘类似的功能~或许我应该设置一个选项，选择缩小还是直接关闭。

2012/6/22 Icelure <
reply@reply.github.com

**Comment by coconut-star** [comment]
那至少有个问题，在loginwindow的时候要关闭掉，这样处理应该是针对mainwindow来做，windows下也是这样的

**Comment by zhanlangsir** [comment]
是的，已经修复~

在 2012年6月22日 下午4:01，Icelure <
reply@reply.github.com
