### ISSUE TITLE
编译错误 

### ISSUE THREAD

**Issue by wxg4net** [zhanlangsir/Qtqq#14]
编译时 出现解决不了错误
/usr/bin/ld: warning: libdl.so.2, needed by /usr/lib/libX11.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: librt.so.1, needed by /usr/lib/libgobject-2.0.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../.intermediate/obj/qqutility.o: undefined reference to symbol 'inflateInit2_'
/usr/bin/ld: note: 'inflateInit2_' is defined in DSO /usr/lib/libz.so.1 so try adding it to the linker command line
/usr/lib/libz.so.1: could not read symbols: Invalid operation

**Comment by shwangdev** [comment]
最好把qt和autotool集成在一起。

**Comment by maplebeats** [comment]
https://github.com/zhanlangsir/Qtqq/issues/6
