### ISSUE TITLE
与多个网友聊天，要开好几个窗口切换不方便啊

### ISSUE THREAD

**Issue by boyll520** [zhanlangsir/Qtqq#15]
能否把聊天窗口做成分页形式的，就像火狐的多标签功能的。一个窗口。与多个网友聊天，要开好几个窗口切换不方便啊

**Comment by zx900930** [comment]
你可以用pidgin-lwqq
我是看中了qtqq的qt, 结果对KDE的支持也还有待改进, 托盘图标还是问号, 消息提示也有点小问题

**Comment by zhanlangsir** [comment]
0.8.0版本开始支持tab页聊天
