### ISSUE TITLE
信息没声音，mpg123 已装

### ISSUE THREAD

**Issue by jouyouyun** [zhanlangsir/Qtqq#17]
rt, 另外，在对话框已存在的情况，来信息页没有提示。
系统：Arch 64bit

**Comment by zhanlangsir** [comment]
于 2012年08月20日 18:13, wen 写道:

> rt, 另外，在对话框已存在的情况，来信息页没有提示。
> 系统：Arch 64bit
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/zhanlangsir/Qtqq/issues/17.
> 
> 可以把~/.config/Qtqq/log.log这个文件发给我看一下吗？
> 另外看一下主菜单里的静音选项有没有选上，测试一下终端里使用mpg123能不能正 
> 常发声~

在对话框已存在的情况，来信息页没有提示，这是正常情况~因为如果聊天窗口已 
经打开，说明你正在聊天，这时候还不停的提示就会挺烦的~(个人感 觉)

**Comment by jouyouyun** [comment]
今天重新编译安装了一遍，就好了。日志文件中只找到了今天的，以前的没发现

**Comment by jouyouyun** [comment]
那能否在对话框上设置一个按钮，来选择是否需要静音？

**Comment by zhanlangsir** [comment]
于 2012年08月22日 18:40, wen 写道:

**Comment by jouyouyun** [comment]
这个我知道，聊天时，如果对话框已存在，来信息页没有提示，我是说在这个对话框上添加  按钮 来决定是否静音。
