### ISSUE TITLE
make无效

### ISSUE THREAD

**Issue by kosl90** [zhanlangsir/Qtqq#2]
用make编译的时候无效啊，说Makefile:66: **\* multiple target patterns.  Stop.

**Comment by zhanlangsir** [comment]
你下载的是qtqq分支的吧。下载qtqq-dev分支的，另外Makefile是linux平台下的，如果你是在win下,先qmake，然后再make~

**Comment by kosl90** [comment]
我用git clone了这份工程，然后进入dev分支，再make也不行，make: **\* No targets specified and no makefile found.  Stop.
我看了一下，这个分支好像没有makefile，我用的是ubuntu11.10，我是不是应该安装qt3-dev-tools之类的东西然后再编译？

**Comment by zhanlangsir** [comment]
是的，你可以安装qt4-dev-tool,然后qmake,再make,如果你是想参与开发，最好就安装,如果只是想使用的话，在download页有编译好的了~直接下载就可以
