### ISSUE TITLE
代码check下来如何编译

### ISSUE THREAD

**Issue by ghost** [zhanlangsir/Qtqq#20]
我对qt一点都不了解，所以也不知道怎么编译， 能否在README中补充一下如何编译出qtqq来，多谢

**Comment by zhanlangsir** [comment]
谢谢提醒，编译方法在这里
http://www.aitilife.com/qtqq

迟点我会补到readme上去的。

2012/8/31 Bai notifications@github.com

**Comment by ghost** [comment]
回复的挺快的，我没有及时来看，呵呵，编译放到README中比较好，因为一般人都会先看这个文件，或者是那个INSTALL，我当时看了这两个文件什么都没有找到，所以才问的，另外在ubuntu12.04 desktop版本中默认没有下边两个库
sudo apt-get install libnotify-dev -y
sudo apt-get install libgtk2.0-dev -y

还有一点，上面回复的链接有一点点问题，应该是不小心造成的，如果能编辑的话，改一下吧

**Comment by picasso250** [comment]
http://www.aitilife.com/qtqq
这个网址访问不了了

我也不会编译
