### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by prehistoricpenguin** [zhanlangsir/Qtqq#24]
“qtqq
qtqq: error while loading shared libraries: liblog4qt.so: cannot open shared object file: No such file or directory”

而liblog4qt.so却是存在于/usr/local/lib（源码版本：qtqq_0.7.2-oneiric，我的linux版本：ubuntu 12.10）

**Comment by zhanlangsir** [comment]
创建一个link到/usr/lib或者直接移动到/usr/lib
