### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by axlecho** [zhanlangsir/Qtqq#29]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
QT_QTWEBKIT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/echo/echo_qtqq/Qtqq/src

-- Configuring incomplete, errors occurred!

Qt 4.8.0
Fedora 17
已切换到dev分支下

**Comment by zhanlangsir** [comment]
fedora下需要安装qtwebkit-devel,其他系统可以搜索一下叫qtwebkit的包,装上就可以了
