### ISSUE TITLE
应该增加Systray单击事件响应

### ISSUE THREAD

**Issue by librehat** [zhanlangsir/Qtqq#30]
如题。
单击Systray应该默认是有新消息时打开对话窗口。没有新消息时，按照KDE下的程序惯例，则单击隐藏主界面（已经隐藏则单击显示出来），而不是什么事情都要右键单击出菜单选择。

此外，程序要调用系统Qt主题设置好一些，有些按钮看起来很奇怪，字体大小貌似也没有使用系统全局的设定。

最后，作者加油啦！现在忙考试，对Qt也不懂，以后有机会来fork一个！

**Comment by zhanlangsir** [comment]
谢谢提醒.另外按ctrl+alt+z可以在没有未读消息时显示界面的额.

**Comment by zhanlangsir** [comment]
单击隐藏/显示主界面已经完成,字体问题我这里没有什么变现,能举个例子吗?

**Comment by librehat** [comment]
嗯，好像字体是我系统的问题还是怎么搞的，在另一个系统下，同样的KDE环境居然没问题。。。
那就剩下UI啦，太多的框框了，比如“发送”按钮，“菜单”按钮，本身按钮就有框框，没必要再套一个方框框，可以考虑用水平线之类的隔开（参考telepathy、konversation之类的设计）
