### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by kericw** [zhanlangsir/Qtqq#31]
[ 60%] Building CXX object src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o
/home/latel/下载/qtqq/src/core/friendimgsender.cpp: In member function ‘virtual FileInfo FriendImgSender::parseResult(const QByteArray&)’:
/home/latel/下载/qtqq/src/core/friendimgsender.cpp:56: error: ‘class QDateTime’ has no member named ‘toMSecsSinceEpoch’
make[2]: **\* [src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o] 错误 1
make[1]: **\* [src/CMakeFiles/qtqq.dir/all] 错误 2
make: **\* [all] 错误 2

平台：debian 6.0.6
dev 分支

**Comment by zhanlangsir** [comment]
你的qt版本低于4.7的~

2013-01-15

湛狼

发件人：kericw
发送时间：2013-01-15 20:02
主题：[Qtqq] 编译时出错 (#31)
收件人："zhanlangsir/Qtqq"Qtqq@noreply.github.com
抄送：

[ 60%] Building CXX object src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o
/home/latel/下载/qtqq/src/core/friendimgsender.cpp: In member function ‘virtual FileInfo FriendImgSender::parseResult(const QByteArray&)’:
/home/latel/下载/qtqq/src/core/friendimgsender.cpp:56: error: ‘class QDateTime’ has no member named ‘toMSecsSinceEpoch’
make[2]: **\* [src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o] 错误 1
make[1]: **\* [src/CMakeFiles/qtqq.dir/all] 错误 2
make: **\* [all] 错误 2
平台：debian 6.0.6
dev 分支
