### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by b4yourback** [zhanlangsir/Qtqq#32]
centos 6.3.完全按照http://www.aitilife.com/qtqq/上手动编译方法来的，出现下面错误
$cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
  -- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found.
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found.
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found.
-- Found Qt-Version 4.6.2
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- checking for module 'x11'
--   found x11, version 1.3
-- checking for module 'zlib'
--   found zlib, version 1.2.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/b4yourback/software/qtqq/release

$make
[  0%] Generating log4qt/helpers/moc_patternformatter.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/patternformatter.h:0: Warning: No relevant classes found. No output generated.
[  0%] Generating log4qt/moc_consoleappender.cxx
[  0%] Generating log4qt/moc_ttcclayout.cxx
[  1%] Generating log4qt/moc_patternlayout.cxx
[  1%] Generating log4qt/moc_simplelayout.cxx
[  1%] Generating log4qt/moc_fileappender.cxx
[  1%] Generating log4qt/moc_dailyrollingfileappender.cxx
[  2%] Generating log4qt/moc_logmanager.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/logmanager.h:0: Warning: No relevant classes found. No output generated.
[  2%] Generating log4qt/moc_log4qt.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/log4qt.h:0: Warning: No relevant classes found. No output generated.
[  2%] Generating log4qt/moc_propertyconfigurator.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/propertyconfigurator.h:0: Warning: No relevant classes found. No output generated.
[  2%] Generating log4qt/varia/moc_stringmatchfilter.cxx
[  3%] Generating log4qt/varia/moc_listappender.cxx
[  3%] Generating log4qt/varia/moc_debugappender.cxx
[  3%] Generating log4qt/varia/moc_levelmatchfilter.cxx
[  4%] Generating log4qt/varia/moc_levelrangefilter.cxx
[  4%] Generating log4qt/varia/moc_denyallfilter.cxx
[  4%] Generating log4qt/varia/moc_nullappender.cxx
[  4%] Generating log4qt/moc_level.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/level.h:0: Warning: No relevant classes found. No output generated.
[  5%] Generating log4qt/moc_basicconfigurator.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/basicconfigurator.h:0: Warning: No relevant classes found. No output generated.
[  5%] Generating log4qt/moc_mdc.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/mdc.h:0: Warning: No relevant classes found. No output generated.
[  5%] Generating log4qt/moc_rollingfileappender.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/rollingfileappender.h:79: Warning: Property declaration maxFileSize has no READ accessor function. The property will be invalid.
[  5%] Generating log4qt/spi/moc_filter.cxx
[  6%] Generating log4qt/moc_loggingevent.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/loggingevent.h:0: Warning: No relevant classes found. No output generated.
[  6%] Generating log4qt/moc_ndc.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/ndc.h:0: Warning: No relevant classes found. No output generated.
[  6%] Generating log4qt/moc_layout.cxx
[  7%] Generating log4qt/moc_loggerrepository.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/loggerrepository.h:0: Warning: No relevant classes found. No output generated.
[  7%] Generating log4qt/moc_appender.cxx
[  7%] Generating log4qt/moc_appenderskeleton.cxx
[  7%] Generating log4qt/moc_writerappender.cxx
[  8%] Generating log4qt/moc_hierarchy.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/hierarchy.h:0: Warning: No relevant classes found. No output generated.
[  8%] Generating log4qt/moc_logger.cxx
[  8%] Generating log4qt/helpers/moc_classlogger.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/classlogger.h:0: Warning: No relevant classes found. No output generated.
[  8%] Generating log4qt/helpers/moc_configuratorhelper.cxx
[  9%] Generating log4qt/helpers/moc_datetime.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/datetime.h:0: Warning: No relevant classes found. No output generated.
[  9%] Generating log4qt/helpers/moc_factory.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/factory.h:0: Warning: No relevant classes found. No output generated.
[  9%] Generating log4qt/helpers/moc_initialisationhelper.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/initialisationhelper.h:0: Warning: No relevant classes found. No output generated.
[  9%] Generating log4qt/helpers/moc_logobject.cxx
[ 10%] Generating log4qt/helpers/moc_logobjectptr.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/logobjectptr.h:0: Warning: No relevant classes found. No output generated.
[ 10%] Generating log4qt/helpers/moc_optionconverter.cxx
/home/b4yourback/software/qtqq/3rdparty/log4qt/src/log4qt/helpers/optionconverter.h:0: Warning: No relevant classes found. No output generated.
Scanning dependencies of target log4qt
[ 10%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/logerror.cpp.o
[ 10%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/initialisationhelper.cpp.o
[ 10%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/optionconverter.cpp.o
[ 11%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/factory.cpp.o
[ 11%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/logobjectptr.cpp.o
[ 11%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/configuratorhelper.cpp.o
[ 11%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/classlogger.cpp.o
[ 12%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/properties.cpp.o
[ 12%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/datetime.cpp.o
[ 12%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/patternformatter.cpp.o
[ 12%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/logobject.cpp.o
[ 13%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/spi/filter.cpp.o
[ 13%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/denyallfilter.cpp.o
[ 13%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/nullappender.cpp.o
[ 14%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/levelrangefilter.cpp.o
[ 14%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/stringmatchfilter.cpp.o
[ 14%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/levelmatchfilter.cpp.o
[ 14%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/listappender.cpp.o
[ 15%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/debugappender.cpp.o
[ 15%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/fileappender.cpp.o
[ 15%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/hierarchy.cpp.o
[ 15%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/appenderskeleton.cpp.o
[ 16%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/rollingfileappender.cpp.o
[ 16%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/basicconfigurator.cpp.o
[ 16%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/consoleappender.cpp.o
[ 17%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/writerappender.cpp.o
[ 17%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/layout.cpp.o
[ 17%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/propertyconfigurator.cpp.o
[ 17%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/loggerrepository.cpp.o
[ 18%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/mdc.cpp.o
[ 18%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/log4qt.cpp.o
[ 18%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/ttcclayout.cpp.o
[ 18%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/loggingevent.cpp.o
[ 19%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/simplelayout.cpp.o
[ 19%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/dailyrollingfileappender.cpp.o
[ 19%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/ndc.cpp.o
[ 19%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/logmanager.cpp.o
[ 20%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/level.cpp.o
[ 20%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/logger.cpp.o
[ 20%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/patternlayout.cpp.o
[ 21%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_consoleappender.cxx.o
[ 21%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_ttcclayout.cxx.o
[ 21%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_patternlayout.cxx.o
[ 21%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_simplelayout.cxx.o
[ 22%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_fileappender.cxx.o
[ 22%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_dailyrollingfileappender.cxx.o
[ 22%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_logmanager.cxx.o
[ 22%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_log4qt.cxx.o
[ 23%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_propertyconfigurator.cxx.o
[ 23%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_stringmatchfilter.cxx.o
[ 23%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_listappender.cxx.o
[ 24%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_debugappender.cxx.o
[ 24%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_levelmatchfilter.cxx.o
[ 24%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_levelrangefilter.cxx.o
[ 24%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_denyallfilter.cxx.o
[ 25%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/varia/moc_nullappender.cxx.o
[ 25%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_level.cxx.o
[ 25%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_basicconfigurator.cxx.o
[ 25%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_mdc.cxx.o
[ 26%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_rollingfileappender.cxx.o
[ 26%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/spi/moc_filter.cxx.o
[ 26%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_loggingevent.cxx.o
[ 26%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_ndc.cxx.o
[ 27%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_layout.cxx.o
[ 27%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_loggerrepository.cxx.o
[ 27%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_appender.cxx.o
[ 28%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_appenderskeleton.cxx.o
[ 28%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_writerappender.cxx.o
[ 28%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_hierarchy.cxx.o
[ 28%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/moc_logger.cxx.o
[ 29%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_classlogger.cxx.o
[ 29%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_configuratorhelper.cxx.o
[ 29%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_datetime.cxx.o
[ 29%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_factory.cxx.o
[ 30%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_initialisationhelper.cxx.o
[ 30%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_logobject.cxx.o
[ 30%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_logobjectptr.cxx.o
[ 31%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_optionconverter.cxx.o
[ 31%] Building CXX object 3rdparty/log4qt/src/CMakeFiles/log4qt.dir/log4qt/helpers/moc_patternformatter.cxx.o
Linking CXX shared library ../../../lib/liblog4qt.so
[ 31%] Built target log4qt
[ 31%] Generating moc_qxtglobalshortcut_p.cxx
/home/b4yourback/software/qtqq/3rdparty/qxtglobalshortcut/qxtglobalshortcut_p.h:0: Warning: No relevant classes found. No output generated.
[ 31%] Generating moc_qxtglobal.cxx
/home/b4yourback/software/qtqq/3rdparty/qxtglobalshortcut/qxtglobal.h:0: Warning: No relevant classes found. No output generated.
[ 31%] Generating moc_qxtglobalshortcut.cxx
Scanning dependencies of target qxtglobalshortcut
[ 32%] Building CXX object 3rdparty/qxtglobalshortcut/CMakeFiles/qxtglobalshortcut.dir/qxtglobalshortcut.cpp.o
[ 32%] Building CXX object 3rdparty/qxtglobalshortcut/CMakeFiles/qxtglobalshortcut.dir/qxtglobalshortcut_x11.cpp.o
[ 32%] Building CXX object 3rdparty/qxtglobalshortcut/CMakeFiles/qxtglobalshortcut.dir/moc_qxtglobal.cxx.o
[ 32%] Building CXX object 3rdparty/qxtglobalshortcut/CMakeFiles/qxtglobalshortcut.dir/moc_qxtglobalshortcut.cxx.o
[ 33%] Building CXX object 3rdparty/qxtglobalshortcut/CMakeFiles/qxtglobalshortcut.dir/moc_qxtglobalshortcut_p.cxx.o
Linking CXX shared library ../../lib/libqxtglobalshortcut.so
[ 33%] Built target qxtglobalshortcut
Scanning dependencies of target jsoncxx
[ 34%] Building CXX object 3rdparty/jsoncpp/src/lib_json/CMakeFiles/jsoncxx.dir/json_reader.cpp.o
[ 34%] Building CXX object 3rdparty/jsoncpp/src/lib_json/CMakeFiles/jsoncxx.dir/json_value.cpp.o
[ 34%] Building CXX object 3rdparty/jsoncpp/src/lib_json/CMakeFiles/jsoncxx.dir/json_writer.cpp.o
Linking CXX shared library ../../../../lib/libjsoncxx.so
[ 34%] Built target jsoncxx
[ 35%] Generating ui_tabwindow.h
[ 35%] Generating core/moc_qqlogincore.cxx
[ 36%] Generating core/moc_qqmsglistener.cxx
/home/b4yourback/software/qtqq/src/core/qqmsglistener.h:0: Warning: No relevant classes found. No output generated.
[ 36%] Generating core/moc_groupchatlog.cxx
/home/b4yourback/software/qtqq/src/core/groupchatlog.h:0: Warning: No relevant classes found. No output generated.
[ 36%] Generating core/moc_friendchatlog.cxx
/home/b4yourback/software/qtqq/src/core/friendchatlog.h:0: Warning: No relevant classes found. No output generated.
[ 36%] Generating core/moc_request.cxx
/home/b4yourback/software/qtqq/src/core/request.h:0: Warning: No relevant classes found. No output generated.
[ 37%] Generating core/moc_msgsender.cxx
[ 37%] Generating core/moc_types.cxx
/home/b4yourback/software/qtqq/src/core/types.h:0: Warning: No relevant classes found. No output generated.
[ 37%] Generating core/moc_qqavatarrequester.cxx
/home/b4yourback/software/qtqq/src/core/qqavatarrequester.h:0: Warning: No relevant classes found. No output generated.
[ 37%] Generating core/moc_groupimgloader.cxx
/home/b4yourback/software/qtqq/src/core/groupimgloader.h:0: Warning: No relevant classes found. No output generated.
[ 38%] Generating core/moc_qqmsg.cxx
/home/b4yourback/software/qtqq/src/core/qqmsg.h:0: Warning: No relevant classes found. No output generated.
[ 38%] Generating core/moc_nameconvertor.cxx
/home/b4yourback/software/qtqq/src/core/nameconvertor.h:0: Warning: No relevant classes found. No output generated.
[ 38%] Generating core/moc_groupimgsender.cxx
/home/b4yourback/software/qtqq/src/core/groupimgsender.h:0: Warning: No relevant classes found. No output generated.
[ 38%] Generating core/moc_qqskinable.cxx
/home/b4yourback/software/qtqq/src/core/qqskinable.h:0: Warning: No relevant classes found. No output generated.
[ 39%] Generating core/moc_qqchatlog.cxx
/home/b4yourback/software/qtqq/src/core/qqchatlog.h:0: Warning: No relevant classes found. No output generated.
[ 39%] Generating core/moc_imgsender.cxx
[ 39%] Generating core/moc_accountmanager.cxx
/home/b4yourback/software/qtqq/src/core/accountmanager.h:0: Warning: No relevant classes found. No output generated.
[ 40%] Generating core/moc_qqitem.cxx
/home/b4yourback/software/qtqq/src/core/qqitem.h:0: Warning: No relevant classes found. No output generated.
[ 40%] Generating core/moc_friendimgsender.cxx
/home/b4yourback/software/qtqq/src/core/friendimgsender.h:0: Warning: No relevant classes found. No output generated.
[ 40%] Generating core/moc_sockethelper.cxx
/home/b4yourback/software/qtqq/src/core/sockethelper.h:0: Warning: No relevant classes found. No output generated.
[ 40%] Generating core/moc_qqchatitem.cxx
/home/b4yourback/software/qtqq/src/core/qqchatitem.h:0: Warning: No relevant classes found. No output generated.
[ 41%] Generating core/moc_imgloader.cxx
[ 41%] Generating core/moc_captchainfo.cxx
/home/b4yourback/software/qtqq/src/core/captchainfo.h:0: Warning: No relevant classes found. No output generated.
[ 41%] Generating core/moc_qqutility.cxx
/home/b4yourback/software/qtqq/src/core/qqutility.h:0: Warning: No relevant classes found. No output generated.
[ 41%] Generating core/moc_singleton.cxx
/home/b4yourback/software/qtqq/src/core/singleton.h:0: Warning: No relevant classes found. No output generated.
[ 42%] Generating core/moc_tasks.cxx
/home/b4yourback/software/qtqq/src/core/tasks.h:0: Warning: No relevant classes found. No output generated.
[ 42%] Generating core/moc_talkable.cxx
[ 42%] Generating core/moc_curr_login_account.cxx
/home/b4yourback/software/qtqq/src/core/curr_login_account.h:0: Warning: No relevant classes found. No output generated.
[ 43%] Generating chatwidget/moc_tabwindow.cxx
[ 43%] Generating chatwidget/moc_qqchatdlg.cxx
[ 43%] Generating chatwidget/moc_friendchatdlg.cxx
[ 43%] Generating chatwidget/moc_groupchatdlg.cxx
[ 44%] Generating chatwidget/moc_sesschatdlg.cxx
[ 44%] Generating chatwidget/moc_chatmsg_processor.cxx
[ 44%] Generating chatwidget/moc_chatdlg_manager.cxx
[ 44%] Generating requestwidget/moc_grouprequestdlg.cxx
[ 45%] Generating requestwidget/moc_friendrequestdlg.cxx
[ 45%] Generating requestwidget/moc_requestmsg_processor.cxx
[ 45%] Generating msgprocessor/moc_msg_processor.cxx
[ 45%] Generating qq_protocol/moc_qq_protocol.cxx
[ 46%] Generating qq_protocol/moc_pollthread.cxx
[ 46%] Generating qq_protocol/request_jobs/moc_job_base.cxx
[ 46%] Generating qq_protocol/request_jobs/moc_friendinfo2_job.cxx
[ 47%] Generating qq_protocol/request_jobs/moc_strangerinfo2_job.cxx
[ 47%] Generating qq_protocol/request_jobs/moc_icon_job.cxx
[ 47%] Generating roster/moc_roster.cxx
[ 47%] Generating rostermodel/moc_roster_model_base.cxx
/home/b4yourback/software/qtqq/src/rostermodel/roster_model_base.h:0: Warning: No relevant classes found. No output generated.
[ 48%] Generating rostermodel/moc_roster_index.cxx
[ 48%] Generating rostermodel/moc_roster_model.cxx
[ 48%] Generating rostermodel/moc_recent_model.cxx
[ 48%] Generating rostermodel/moc_contact_proxy_model.cxx
[ 49%] Generating skinengine/moc_qqskinengine.cxx
[ 49%] Generating skinengine/moc_msgstyle_manager.cxx
/home/b4yourback/software/qtqq/src/skinengine/msgstyle_manager.h:0: Warning: No relevant classes found. No output generated.
[ 49%] Generating soundplayer/moc_soundplayer.cxx
/home/b4yourback/software/qtqq/src/soundplayer/soundplayer.h:0: Warning: No relevant classes found. No output generated.
[ 50%] Generating storage/moc_storage.cxx
/home/b4yourback/software/qtqq/src/storage/storage.h:0: Warning: No relevant classes found. No output generated.
[ 50%] Generating strangermanager/moc_stranger_manager.cxx
[ 50%] Generating utils/moc_request_callback.cxx
[ 50%] Generating utils/moc_contact_status.cxx
/home/b4yourback/software/qtqq/src/utils/contact_status.h:0: Warning: No relevant classes found. No output generated.
[ 51%] Generating utils/moc_icon_decorator.cxx
/home/b4yourback/software/qtqq/src/utils/icon_decorator.h:0: Warning: No relevant classes found. No output generated.
[ 51%] Generating trayicon/moc_systemtray.cxx
[ 51%] Generating moc_chatlogwin.cxx
[ 51%] Generating moc_frienditem.cxx
[ 52%] Generating moc_qtqq.cxx
[ 52%] Generating moc_frienditemmodel.cxx
[ 52%] Generating moc_qqtextedit.cxx
[ 52%] Generating moc_moveablehandler.cxx
/home/b4yourback/software/qtqq/src/moveablehandler.h:0: Warning: No relevant classes found. No output generated.
[ 53%] Generating moc_qqtitlebar.cxx
[ 53%] Generating moc_recentlistitemmodel.cxx
[ 53%] Generating moc_groupitemmodel.cxx
/home/b4yourback/software/qtqq/src/groupitemmodel.h:0: Warning: No relevant classes found. No output generated.
[ 54%] Generating moc_msgbrowse.cxx
[ 54%] Generating moc_mainwindow.cxx
[ 54%] Generating moc_loginwin.cxx
[ 54%] Generating moc_qqfacepanel.cxx
[ 55%] Generating moc_qqiteminfohelper.cxx
/home/b4yourback/software/qtqq/src/qqiteminfohelper.h:0: Warning: No relevant classes found. No output generated.
[ 55%] Generating moc_qqwidget.cxx
[ 55%] Generating moc_qqitemmodel.cxx
[ 55%] Generating moc_friendinfodlg.cxx
/home/b4yourback/software/qtqq/src/friendinfodlg.h:0: Warning: No relevant classes found. No output generated.
[ 56%] Generating moc_qqglobal.cxx
/home/b4yourback/software/qtqq/src/qqglobal.h:0: Warning: No relevant classes found. No output generated.
[ 56%] Generating moc_friendsearcher.cxx
/home/b4yourback/software/qtqq/src/friendsearcher.h:0: Warning: No relevant classes found. No output generated.
[ 56%] Generating moc_friendsearchlineedit.cxx
/home/b4yourback/software/qtqq/src/friendsearchlineedit.h:0: Warning: No relevant classes found. No output generated.
[ 57%] Generating ui_captcha.h
[ 57%] Generating ui_friendinfodlg.h
[ 57%] Generating ui_loginwin.h
[ 57%] Generating ui_chatlogwin.h
[ 58%] Generating ui_friendrequestdlg.h
[ 58%] Generating ui_mainwindow.h
[ 58%] Generating ui_groupchatdlg.h
Warning: name layoutWidget is already used
[ 58%] Generating ui_friendchatdlg.h
'' isn't a valid widget
[ 59%] Generating ui_grouprequestdlg.h
[ 59%] Generating ui_qqfacepanel.h
[ 59%] Generating ui_sesschatdlg.h
'' isn't a valid widget
Scanning dependencies of target qtqq
[ 60%] Building CXX object src/CMakeFiles/qtqq.dir/core/qqlogincore.cpp.o
[ 60%] Building CXX object src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o
/home/b4yourback/software/qtqq/src/core/friendimgsender.cpp: In member function ‘virtual FileInfo FriendImgSender::parseResult(const QByteArray&)’:
/home/b4yourback/software/qtqq/src/core/friendimgsender.cpp:56: 错误：‘class QDateTime’没有名为‘toMSecsSinceEpoch’的成员
make[2]: **\* [src/CMakeFiles/qtqq.dir/core/friendimgsender.cpp.o] 错误 1
make[1]: **\* [src/CMakeFiles/qtqq.dir/all] 错误 2
make: **\* [all] 错误 2

**Comment by zhanlangsir** [comment]
@b4yourback 你的qt版本低于4.8.
