### ISSUE TITLE
0.4.2版本一直卡在登陆界面

### ISSUE THREAD

**Issue by zx900930** [zhanlangsir/Qtqq#4]
Ubuntu 12.04
点击登陆，输完验证码后就没反应了

**Comment by zhanlangsir** [comment]
其他版本会吗？0.4.3-alpha版已经更新了，可以试试~如果还是卡的话，麻烦留一下联系方式好吗？我联系你调试一下。因为现在还没有加入log方面的功能，所以只能这样做了~

**Comment by zx900930** [comment]
试了0.4.3-alpha版本
1.默认记住了QQ 543286489 的帐号密码 
2.还是无法登录

之前一直用GTKQQ, 没有问题
我的联系方式zx900930#gmail.com  或者twitter @zx900930

**Comment by zx900930** [comment]
上图两张
http://o7007-myimg.stor.sinaapp.com/1335845093elpf.png
http://o7007-myimg.stor.sinaapp.com/1335845166gjzp.png
