### ISSUE TITLE
最新的在ubuntu11.04下qt4.7.2无法编译成功

### ISSUE THREAD

**Issue by shnwang** [zhanlangsir/Qtqq#5]
2012.06.04 chekout 的代码 无法编译成功

**Comment by zhanlangsir** [comment]
最新代码是在qtqq-dev分支。能把编译失败的错误信息一起发上来吗？

**Comment by shnwang** [comment]
WARNING: Failure to find: ui_login.h
WARNING: Failure to find: friendimgloader.h
WARNING: Failure to find: groupimgloader.h

以上是qmake的警告

qqtextedit.cpp: In member function ‘void QQTextEdit::appendDocument(const
QTextDocument_)’:
qqtextedit.cpp:24:12: error: ‘class QTextBlockFormat’ has no member named
‘setLineHeight’
qqtextedit.cpp:24:29: error: ‘LineDistanceHeight’ is not a member of
‘QTextBlockFormat’
qqtextedit.cpp: In member function ‘void QQTextEdit::insertWord(const
QString&, QFont, QColor, int)’:
qqtextedit.cpp:53:18: error: ‘class QTextBlockFormat’ has no member named
‘setLineHeight’
qqtextedit.cpp:53:35: error: ‘LineDistanceHeight’ is not a member of
‘QTextBlockFormat’
qqtextedit.cpp: In member function ‘void QQTextEdit::setRealImg(const
QString&, const QString&)’:
qqtextedit.cpp:133:5: error: ‘QFile’ was not declared in this scope
qqtextedit.cpp:133:11: error: expected ‘;’ before ‘file’
qqtextedit.cpp:134:5: error: ‘file’ was not declared in this scope
make: *_\* [qqtextedit.o] 错误 1

以上是make的错误

谢谢

2012/6/4 O湛狼O <
reply@reply.github.com

**Comment by zhanlangsir** [comment]
qt版本不对~要4.8以上，还有应该checkout qtqq-dev分支，主分支由于某些原因很久没merge了。
