### ISSUE TITLE
为啥更新很慢

### ISSUE THREAD

**Issue by Pantynopants** [zhanlangsir/Qtqq#54]
commit都2年前的了

**Comment by lieefu** [comment]
https://github.com/vipjeffreylee/QQrobot 这个新点

**Comment by younfor** [comment]
没时间弄了来自我的华为手机-------- 原始邮件 --------主题：Re: [Qtqq] 为啥更新很慢 (#54)发件人：Neuldp 收件人：zhanlangsir/Qtqq 抄送：Closed #54.
