### ISSUE TITLE
64位arch编译失败

### ISSUE THREAD

**Issue by maplebeats** [zhanlangsir/Qtqq#6]
/usr/bin/ld: ../zhanlangsir-Qtqq-3446bee/.intermediate/obj/qqutility.o: undefined reference to symbol 'inflateInit2_'
/usr/bin/ld: note: 'inflateInit2_' is defined in DSO /usr/lib/libz.so.1 so try adding it to the linker command line
/usr/lib/libz.so.1: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: **\* [qtqq] Error 1

**Comment by zhanlangsir** [comment]
需要安装zlib

**Comment by maplebeats** [comment]
^_^[maplebeats@otaku:~]$ pacman -Q zlib
zlib 1.2.7-1
我检查了的，有libz.so文件。。。

**Comment by zhanlangsir** [comment]
把他link进项目看看，可以在qtqq.pro的

unix:LIBS += ./libs/libjson.so

一行中添加，

unix:LIBS += ./libs/libjson.so \
                    your_zlib_library_path
