### ISSUE TITLE
qtqq-dev cannot be compiled

### ISSUE THREAD

**Issue by Cravix** [zhanlangsir/Qtqq#7]
"qmake -project" works, but when execute "qmake", i get following stderr:
<code>RCC: Warning: No resources in 'misc/img.qrc'.</code>
btw, i'm using archlinux with qt 4.8.2.

BTW, i can use qtqq-bin you packed, but it always prompt that pas unmatch username... maybe there's something wrong?

**Comment by zhanlangsir** [comment]
You can ignore this warning.It's not the reason of compiled failed.
It must has other error to stop the compile.

And, which version of qtqq did you download?  If it's not qtqqv0.5.0, you
should update it.
If  it's qtqqv0.5.0, you can find a file name log.log in qtqq's root
directory, you can send it to me.

2012/6/18 Cravix <
reply@reply.github.com

**Comment by Cravix** [comment]
en, you're right, ignore the warning and it works...
but, still cannot be compiled= =
stdout of make as follows.
(put most of stdout on http://pastebin.ca/2162418 ,maybe my glibc is too new? don't really get it...)

<code>src/core/qqavatarrequester.h:6:22: fatal error: QTcpSocket: No such file or directory
compilation terminated.
make: **\* [frienditemmodel.o] Error 1</code>

**Comment by zhanlangsir** [comment]
I made some changes at qtqq-dev branch just now, you can checkout the
newest code and try to complied it.
Btw, you should check if you install the libqt4-network library(at my
ubuntu12.04, it named this).
If not, you should install it.

2012/6/18 Cravix <
reply@reply.github.com

**Comment by Cravix** [comment]
well, still doesn't work here:
in src/frienditemmodel.cpp gcc cannot find QTcpSocket and json, and after i modified it to be consistent with the head file folder in /usr/include, i got this:
<code>g++ -c -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc -Isrc/core -Iinclude/zlib -I3rdparty/qxtglobalshortcut -I3rdparty/jsoncpp/src -I3rdparty/log4qt/tests -I. -I. -o frienditemmodel.o src/frienditemmodel.cpp
src/frienditemmodel.cpp: In member function ‘virtual void FriendItemModel::parse(const QByteArray&, NameConvertor*)’:
src/frienditemmodel.cpp:12:5: error: ‘Json’ has not been declared
src/frienditemmodel.cpp:12:18: error: expected ‘;’ before ‘reader’
#and so on...</code>
i think the problem is, you use too much direct include like "#include "include/json.h"", which is related to the pack manner of distros,
in my opinion, it's better to use cmake or pkg-config instead to do that, or it'll be imcompatible with other distros = =

**Comment by Cravix** [comment]
oh my... seems i'm wrong here. but still, there is something wrong:
the gcc option shows: -I3rdparty/jsoncpp/src, but no -I3rdparty/jsoncpp here(which #include "include/json.h" need), maybe you should correct it= =
and, the QTcpSocket is in /usr/include/QtNetwork under arch(differ from ubuntu?), so i still recommend you to use pkg-config... eh.

**Comment by Cravix** [comment]
eh, anyway, seems i must check *.pro anyway and adjust it, i got really messed up now= =

**Comment by zhanlangsir** [comment]
You can find json.h,located in qtqq/3rdparty/jsoncpp/include/json.h.
And open it, modify the thirteen line from "features.h" to
"json_features.h".Then, complied again.
I'm so sorry for this mistake.

But i don't know why the QTcpSocket head file is not found. Maybe you can
changed the qtqq.pro.
I upload a qtqq.pro file.you can replace your qtqq.pro to it.
In qtqq.pro, i just add the location of you QTcpSocket file to INCLUDEPATH,
you can find this change
at thirteen line.If "/usr/include/QtNetwork" it's a wrong location, you can
change it.

If this still can't work, i think you can replace the "QTcpSocket" to its
full path like "/usr/include/QtNetwork/qtcpsocket.h".

Btw, are you chinese? My english is bad. Can you understanding what i mean?

2012/6/19 Cravix <
reply@reply.github.com

**Comment by Cravix** [comment]
in fact i'm an alien from outer space, but i can speak chinese as native speaks~ i just get used to write english on IRC. so,  feel free to use chinese, and if need i'll too :-)
and, i've searched the aur of archlinux and found many qt packages are builded using cmake, maybe it has more compatibility? why not give a try:-D

**Comment by Cravix** [comment]
oh my... sorry. i didn't notice that i don't need to do "qmake -project" first, and maybe that's the problem= =i'll try recompile now.
