### ISSUE TITLE
qtqq很棒，希望能设置字体

### ISSUE THREAD

**Issue by fuhaoyun** [zhanlangsir/Qtqq#8]
不能设置字体（颜色等），这样用起来不方便

另外，我在ubuntu 12.04 unity/64位使用，发现信息提示看起来不协调

——————————————————————————————————

我在终端下执行（添加qtqq）
gsettings set com.canonical.Unity.Panel systray-whitelist "['JavaEmbeddedFrame', 'skype','qq','qtqq','ibus','fcitx', 'Wine', 'Update-notifier']  "后，可以在指示器栏显示了，希望新版本能默认自动加入，因为有的linux新手不知道这个做法（我以前就是如此，呵呵）

打开qtqq后，在顶部指示器栏点击一下qtqq图标发现左侧边栏的qtqq图标自动消失——太棒了，节省了空间，少占用一个运行程序图标空间。非常喜欢这个！！

其实就是最小化后自动隐藏侧边栏图标

**Comment by zhanlangsir** [comment]
发现一个问题，在最小化后关闭聊天窗口会自动关闭qq，已经修复，还没上传新版.

**Comment by zhanlangsir** [comment]
另外，你指的字体颜色是界面的字体颜色还是聊天信息的字体颜色呢？

**Comment by coconut-star** [comment]
聊天信息的字体应该是不用处理的吧，因为好像本来每个人都能有自己的颜色和字体

**Comment by fuhaoyun** [comment]
于 2012年06月20日 08:43, O湛狼O 写道:

> 另外，你指的字体颜色是界面的字体颜色还是聊天信息的字体颜色呢？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zhanlangsir/Qtqq/issues/8#issuecomment-6442340
> 
> 聊天信息的字体颜色！

还有刚发现一个状况：
群消息不能显示备注的用户名

谢谢回复，辛苦了！

**Comment by chhx** [comment]
聊天信息的字体 我这里看不清,不知该怎么调..

**Comment by zhanlangsir** [comment]
是所有信息都看不清楚吗？太小还是发虚？

2012/7/14 chhx <
reply@reply.github.com

**Comment by chhx** [comment]
输入框、标题、历史记录的字体都很好
聊天信息的字体不一样 好像是没有被渲染 截图http://126.am/BvwbT0

**Comment by fuhaoyun** [comment]
于 2012年07月15日 16:13, O湛狼O 写道:

**Comment by zhanlangsir** [comment]
现在没有在程序中设置字体的方法,如果你熟系css的话,可以在skins/messagestyle/adium目录的main.css中修改.

.tableBubble .message {
font-size:11px;
}

可以修改这里的font-size和font-family
